#!/bin/bash
set -euo pipefail

chrome="$(which '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' google-chrome google-chrome-stable | head -1 || true)"
if [ -z "$chrome" ]; then
  echo "error: could not find Google Chrome on the system" >&2
  exit 1
fi

chrome_log=/dev/null
CI="${CI:-}"
[ -z "$CI" ] || chrome_log=./chrome.log

chrome_args=(
  --headless
  --disable-gpu
  --no-sandbox
  --remote-debugging-port=9090
  --no-default-browser-check
  --no-first-run
  --disable-default-apps
  --disable-popup-blocking
  --disable-translate
  --disable-background-timer-throttling
  --disable-renderer-backgrounding
  --disable-device-discovery-notifications
)

[ -z "$CI" ] || echo "$chrome" "${chrome_args[@]}"
"$chrome" "${chrome_args[@]}" &>"$chrome_log" &
trap "kill $!" EXIT
sleep 1

STATUS=0
node test/runner.js test/test*.html || STATUS=$?

[ $STATUS -eq 0 ] || [ -z "$CI" ] || cat "$chrome_log"
exit $STATUS
